### ISSUE TITLE
Relocatable option is enabled by default

### ISSUE THREAD

**Issue by homebysix** [scriptingosx/quickpkg#2]
The quickpkg read me says:

> All quickpkg does is identify an application bundle and package it in a way that the package will install that application bundle into the /Applications folder. If the application needs other files (libraries, frameworks, configuration files, license files, preferences etc.) to run and work they are your responsibility.

But it seems that quickpkg allows [bundle relocation](https://developer.apple.com/library/content/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW87) by default, so it's possible that an app may not be installed in the Applications folder where expected.

Might you consider switching relocation to false by default, to align quickpkg's behavior to the stated goal? Thanks!

**Comment by scriptingosx** [comment]
this idea has been on my to-do for a while now. I needed to re-write a large part of the script to make it work. However, I think it is better for it now.

I added an argument `--[no-]relocatable` to control the behavior. quickpkg will create non-relocatable pkgs by default, since I believe this is usually the preferred behavior for admins.

Can you test this version?

https://github.com/scriptingosx/quickpkg/commit/067fe6a8ed907fe8e97b9e970490527c10ac5df7

**Comment by scriptingosx** [comment]
Integrated into 0.5: https://github.com/scriptingosx/quickpkg/releases/tag/v0.5

**Comment by scriptingosx** [comment]
See more here: http://scriptingosx.com/2017/05/relocatable-package-installers-and-quickpkg-update/

**Comment by homebysix** [comment]
Works great! Thank you.
